 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/skiresorts", type: :request do
  # Skiresort. As you add validations to Skiresort, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Skiresort.create! valid_attributes
      get skiresorts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      skiresort = Skiresort.create! valid_attributes
      get skiresort_url(skiresort)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_skiresort_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      skiresort = Skiresort.create! valid_attributes
      get edit_skiresort_url(skiresort)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Skiresort" do
        expect {
          post skiresorts_url, params: { skiresort: valid_attributes }
        }.to change(Skiresort, :count).by(1)
      end

      it "redirects to the created skiresort" do
        post skiresorts_url, params: { skiresort: valid_attributes }
        expect(response).to redirect_to(skiresort_url(Skiresort.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Skiresort" do
        expect {
          post skiresorts_url, params: { skiresort: invalid_attributes }
        }.to change(Skiresort, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post skiresorts_url, params: { skiresort: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested skiresort" do
        skiresort = Skiresort.create! valid_attributes
        patch skiresort_url(skiresort), params: { skiresort: new_attributes }
        skiresort.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the skiresort" do
        skiresort = Skiresort.create! valid_attributes
        patch skiresort_url(skiresort), params: { skiresort: new_attributes }
        skiresort.reload
        expect(response).to redirect_to(skiresort_url(skiresort))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        skiresort = Skiresort.create! valid_attributes
        patch skiresort_url(skiresort), params: { skiresort: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested skiresort" do
      skiresort = Skiresort.create! valid_attributes
      expect {
        delete skiresort_url(skiresort)
      }.to change(Skiresort, :count).by(-1)
    end

    it "redirects to the skiresorts list" do
      skiresort = Skiresort.create! valid_attributes
      delete skiresort_url(skiresort)
      expect(response).to redirect_to(skiresorts_url)
    end
  end
end
